
type CampagnoloComponent = {
    name: string;
    brand: 'Campagnolo';
    series: string;
    model: string;
    system: 'Drivetrain' | 'Brakes' | 'Wheelset';
    size?: string;
};

export const CAMPAGNOLO_COMPONENTS: CampagnoloComponent[] = [
    // Super Record
    { name: 'Shifter', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Wireless', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record EPS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record EPS', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Wireless', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record EPS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record mechanical', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Wireless', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record EPS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Wireless', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Ultra-Torque', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Ultra-Torque', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record C12', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Super Record', model: 'Chorus 11 Speed (compatible)', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO 45', system: 'Wheelset' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO 60', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO 45 Disc', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Super Record', model: 'Bora Ultra WTO 60 Disc', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Wireless', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Disc Brake', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record EPS/Mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Super Record', model: 'Super Record Rim Brake', system: 'Brakes' },

    // Record
    { name: 'Shifter', brand: 'Campagnolo', series: 'Record', model: 'Record EPS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Record', model: 'Record mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Record', model: 'Record EPS', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Record', model: 'Record mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Record', model: 'Record EPS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Record', model: 'Record mechanical', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Record', model: 'Record EPS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Record', model: 'Record mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Record', model: 'Record Ultra-Torque', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Record', model: 'Record Ultra-Torque', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Record', model: 'Record', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Record', model: 'Record', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Record', model: 'Chorus C12', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Record', model: 'Chorus 11 Speed (compatible)', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Record', model: 'Shamal Carbon', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Record', model: 'Shamal Ultra', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Record', model: 'Shamal Carbon', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Record', model: 'Shamal Carbon Disc', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Record', model: 'Record EPS/Mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Record', model: 'Record Disc Brake', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Record', model: 'Record EPS/Mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Record', model: 'Record Rim Brake', system: 'Brakes' },

    // Chorus
    { name: 'Shifter', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus Ultra-Torque', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus Ultra-Torque', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus C12', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus 11 Speed', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Chorus', model: 'Khamsin', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Chorus', model: 'Scirocco', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Chorus', model: 'Scirocco Disc', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus Disc Brake', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Chorus', model: 'Chorus Rim Brake', system: 'Brakes' },

    // Potenza
    { name: 'Shifter', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza mechanical', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza mechanical', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza Ultra-Torque', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza 11 Speed', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Potenza', model: 'Calima', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Potenza', model: 'Calima', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Potenza', model: 'Calima C17', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza Disc Brake', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza mechanical', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Potenza', model: 'Potenza Rim Brake', system: 'Brakes' },

    // Ekar
    { name: 'Shifter', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar Ergopower', system: 'Drivetrain', size: '13' },
    { name: 'Front Derailleur', brand: 'Campagnolo', series: 'Ekar', model: 'N/A', system: 'Drivetrain', size: '1' },
    { name: 'Rear Derailleur', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar', system: 'Drivetrain', size: '13' },
    { name: 'Crankset', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar Pro-Tech', system: 'Drivetrain', size: '1x13' },
    { name: 'Cassette', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar', system: 'Drivetrain', size: '13' },
    { name: 'Chain', brand: 'Campagnolo', series: 'Ekar', model: 'C13 Chain', system: 'Drivetrain', size: '13' },
    { name: 'Hub', brand: 'Campagnolo', series: 'Ekar', model: 'Shamal Carbon', system: 'Wheelset', size: '13' },
    { name: 'Rim', brand: 'Campagnolo', series: 'Ekar', model: 'Levante Carbon', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Campagnolo', series: 'Ekar', model: 'Levante Carbon', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar Ergopower', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Campagnolo', series: 'Ekar', model: 'Ekar Disc Brake', system: 'Brakes' },
];
