
type PedalComponent = {
    name: 'Pedal';
    brand: string;
    model: string;
    system: 'Drivetrain';
};

export const PEDAL_COMPONENTS: PedalComponent[] = [
    { name: 'Pedal', brand: 'Shimano', model: 'Ultegra R8000', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'Dura-Ace R9100', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: '105 R7000', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-M520', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-M8100', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-M324', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-EH500', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-R550', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-EF202', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'GR500', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-M8120', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-T8000', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Shimano', model: 'PD-M540', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Keo 2 Max', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Keo Classic 3', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Keo Blade Carbon Ceramic', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'X-Track Race Carbon Ti', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'X-Track', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Trail Fusion', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Geo City Grip', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Trail Roc+', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Look', model: 'Geo City', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Eggbeater 3', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Mallet E', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Candy 1', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Candy 7', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Stamp 1', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Stamp 3', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Stamp 7', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: 'Double Shot 3', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Crankbrothers', model: '5050', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'XPRO 10', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'XPRO 12', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'XPRO 15', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'ATAC XC 6', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'ATAC XC 2', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'ATAC XC 8', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Time', model: 'Speciale', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Wahoo', model: 'Speedplay Zero', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Wahoo', model: 'Speedplay Aero', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Wahoo', model: 'Speedplay Comp', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Garmin', model: 'Rally RK200', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Garmin', model: 'Rally RS200', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Garmin', model: 'Rally XC200', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Nukeproof', model: 'Horizon Pro', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'RaceFace', model: 'Chester', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'RaceFace', model: 'Aeffect', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'RaceFace', model: 'Atlas', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'OneUp Components', model: 'Composite', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'OneUp Components', model: 'Wave', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'OneUp Components', model: 'Aluminum', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'DMR', model: 'Vault', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'DMR', model: 'V6', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'HT Components', model: 'T2', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'HT Components', model: 'PA03A', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Favero', model: 'Assioma Pro MX-2', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Hope', model: 'Union RC', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Hope', model: 'F22', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Deity', model: 'TMAC', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Deity', model: 'Deftrap', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Wolf Tooth', model: 'Waveform', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Ritchey', model: 'Comp XC', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'PNW', model: 'Range Composite', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Chromag', model: 'Dagga', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Redshift', model: 'Arclight', system: 'Drivetrain' },
    { name: 'Pedal', brand: 'Spank', model: 'Spike', system: 'Drivetrain' },
];
