
import type { ServiceProvider } from './types';

export const SERVICE_PROVIDERS_DATA: Omit<ServiceProvider, 'id'>[] = [
  {
    name: 'Velocity Bike Works',
    shopName: 'Velocity Bike Works',
    logoUrl: 'https://placehold.co/100x100.png',
    services: ['repairs', 'bike-fitting'],
    address: '123 Main Street',
    city: 'Metropolis',
    province: 'SK',
    postalCode: 'S4P 3C8',
    country: 'Canada',
    phone: '306-555-1234',
    website: 'https://www.velocitybikes.com',
    lat: 50.4452,
    lng: -104.6189,
    averageRating: 4.8,
    ratingCount: 124,
    availability: 'Mon-Sat: 10am-6pm',
    dropOff: true,
    valetService: false,
  },
  {
    name: 'The Fit Lab',
    shopName: 'The Fit Lab',
    logoUrl: 'https://placehold.co/100x100.png',
    services: ['bike-fitting'],
    address: '456 Oak Avenue',
    city: 'Metropolis',
    province: 'SK',
    postalCode: 'S4P 3D1',
    country: 'Canada',
    phone: '306-555-5678',
    website: 'https://www.thefitlab.com',
    lat: 50.4547,
    lng: -104.6067,
    averageRating: 5.0,
    ratingCount: 88,
    availability: 'By Appointment',
    dropOff: false,
    valetService: true,
  },
];
