
type ShimanoComponent = {
    name: string;
    brand: 'Shimano';
    series: string;
    model: string;
    system: 'Drivetrain' | 'Brakes' | 'Wheelset';
    size?: string;
};

export const SHIMANO_COMPONENTS: ShimanoComponent[] = [
    // Dura-Ace
    { name: 'Shifter', brand: 'Shimano', series: 'Dura-Ace', model: 'ST-R9270', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Dura-Ace', model: 'ST-R9250', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Dura-Ace', model: 'ST-R9170', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'Dura-Ace', model: 'ST-R9150', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Dura-Ace', model: 'FD-R9250', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Dura-Ace', model: 'FD-R9150', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Dura-Ace', model: 'RD-R9250', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Dura-Ace', model: 'RD-R9150', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Dura-Ace', model: 'FC-R9200', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Dura-Ace', model: 'FC-R9100', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Shimano', series: 'Dura-Ace', model: 'CS-R9200-12', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'Dura-Ace', model: 'CS-R9100', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'Dura-Ace', model: 'CN-M9100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'Dura-Ace', model: 'CN-HG901-11', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'Dura-Ace', model: 'FH-R9270', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: 'Dura-Ace', model: 'FH-R9170', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Shimano', series: 'Dura-Ace', model: 'WH-R9270-C36-TL', system: 'Wheelset' },
    { name: 'Rim', brand: 'Shimano', series: 'Dura-Ace', model: 'WH-R9270-C50-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'Dura-Ace', model: 'WH-R9270-C36-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'Dura-Ace', model: 'WH-R9270-C50-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Dura-Ace', model: 'BL-R9270', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Dura-Ace', model: 'BR-R9270', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Dura-Ace', model: 'BL-R9170', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Dura-Ace', model: 'BR-R9170', system: 'Brakes' },

    // Ultegra
    { name: 'Shifter', brand: 'Shimano', series: 'Ultegra', model: 'ST-R8170', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Ultegra', model: 'ST-R8150', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Ultegra', model: 'ST-R8070', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'Ultegra', model: 'ST-R8050', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Ultegra', model: 'FD-R8150', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Ultegra', model: 'FD-R8050', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Ultegra', model: 'RD-R8150', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Ultegra', model: 'RD-R8050', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Ultegra', model: 'FC-R8100', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Ultegra', model: 'FC-R8000', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Shimano', series: 'Ultegra', model: 'CS-R8100', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'Ultegra', model: 'CS-R8000', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'Ultegra', model: 'CN-M8100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'Ultegra', model: 'CN-HG701-11', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'Ultegra', model: 'FH-R8170', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: 'Ultegra', model: 'FH-R8070', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Shimano', series: 'Ultegra', model: 'WH-R8170-C36-TL', system: 'Wheelset' },
    { name: 'Rim', brand: 'Shimano', series: 'Ultegra', model: 'WH-R8170-C50-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'Ultegra', model: 'WH-R8170-C36-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'Ultegra', model: 'WH-R8170-C50-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Ultegra', model: 'BL-R8170', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Ultegra', model: 'BR-R8170', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Ultegra', model: 'BL-R8070', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Ultegra', model: 'BR-R8070', system: 'Brakes' },

    // 105
    { name: 'Shifter', brand: 'Shimano', series: '105', model: 'ST-R7170', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: '105', model: 'ST-R7000', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Shimano', series: '105', model: 'FD-R7150', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: '105', model: 'FD-R7000', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: '105', model: 'RD-R7150', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: '105', model: 'RD-R7000', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Shimano', series: '105', model: 'FC-R7100', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: '105', model: 'FC-R7000', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Shimano', series: '105', model: 'CS-HG710-12', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: '105', model: 'CS-HG700-11', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: '105', model: 'CN-M7100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: '105', model: 'CN-HG601-11', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: '105', model: 'FH-R7170', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: '105', model: 'FH-R7070', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Shimano', series: '105', model: 'WH-RS710-C32-TL', system: 'Wheelset' },
    { name: 'Rim', brand: 'Shimano', series: '105', model: 'WH-RS710-C46-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: '105', model: 'WH-RS710-C32-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: '105', model: 'WH-RS710-C46-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: '105', model: 'BL-R7170', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: '105', model: 'BR-R7170', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: '105', model: 'BL-R7070', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: '105', model: 'BR-R7070', system: 'Brakes' },

    // Tiagra
    { name: 'Shifter', brand: 'Shimano', series: 'Tiagra', model: 'ST-4700', system: 'Drivetrain', size: '10' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Tiagra', model: 'FD-4700', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Tiagra', model: 'RD-4700', system: 'Drivetrain', size: '10' },
    { name: 'Crankset', brand: 'Shimano', series: 'Tiagra', model: 'FC-4700', system: 'Drivetrain', size: '2x10' },
    { name: 'Cassette', brand: 'Shimano', series: 'Tiagra', model: 'CS-HG500-10', system: 'Drivetrain', size: '10' },
    { name: 'Chain', brand: 'Shimano', series: 'Tiagra', model: 'CN-HG54', system: 'Drivetrain', size: '10' },
    { name: 'Hub', brand: 'Shimano', series: 'Tiagra', model: 'FH-RS400', system: 'Wheelset', size: '10' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Tiagra', model: 'BL-4700', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Tiagra', model: 'BR-4700', system: 'Brakes' },

    // GRX
    { name: 'Shifter', brand: 'Shimano', series: 'GRX', model: 'ST-RX820', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'GRX', model: 'ST-RX810', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'GRX', model: 'ST-RX610', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'GRX', model: 'ST-RX600', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'GRX', model: 'ST-RX400', system: 'Drivetrain', size: '10' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'GRX', model: 'FD-RX810', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'GRX', model: 'FD-RX400', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'GRX', model: 'RD-RX820', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'GRX', model: 'RD-RX810', system: 'Drivetrain', size: '11' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'GRX', model: 'RD-RX600', system: 'Drivetrain', size: '11' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'GRX', model: 'RD-RX400', system: 'Drivetrain', size: '10' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX820-1', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX820-2', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX810-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX810-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX610-1', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX600-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX600-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'GRX', model: 'FC-RX400', system: 'Drivetrain', size: '2x10' },
    { name: 'Cassette', brand: 'Shimano', series: 'GRX', model: 'CS-M8100-12', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'GRX', model: 'CS-M7100-12', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'GRX', model: 'CS-M8000', system: 'Drivetrain', size: '11' },
    { name: 'Cassette', brand: 'Shimano', series: 'GRX', model: 'CS-HG500-10', system: 'Drivetrain', size: '10' },
    { name: 'Chain', brand: 'Shimano', series: 'GRX', model: 'CN-M8100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'GRX', model: 'CN-HG701-11', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'GRX', model: 'CN-HG54', system: 'Drivetrain', size: '10' },
    { name: 'Hub', brand: 'Shimano', series: 'GRX', model: 'FH-RX810', system: 'Wheelset', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'GRX', model: 'FH-RS470', system: 'Wheelset', size: '10' },
    { name: 'Rim', brand: 'Shimano', series: 'GRX', model: 'WH-RX870-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'GRX', model: 'WH-RX870-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'GRX', model: 'BL-RX820', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'GRX', model: 'BR-RX820', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'GRX', model: 'BL-RX810', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'GRX', model: 'BR-RX810', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'GRX', model: 'BL-RX600', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'GRX', model: 'BR-RX400', system: 'Brakes' },

    // CUES
    { name: 'Shifter', brand: 'Shimano', series: 'CUES', model: 'SL-U8000', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'CUES', model: 'SL-U6000', system: 'Drivetrain', size: '10' },
    { name: 'Shifter', brand: 'Shimano', series: 'CUES', model: 'SL-U4000', system: 'Drivetrain', size: '9' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'CUES', model: 'FD-U8000', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'CUES', model: 'FD-U6000', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'CUES', model: 'RD-U8000', system: 'Drivetrain', size: '11' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'CUES', model: 'RD-U6000', system: 'Drivetrain', size: '10' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'CUES', model: 'RD-U4000', system: 'Drivetrain', size: '9' },
    { name: 'Crankset', brand: 'Shimano', series: 'CUES', model: 'FC-U8000-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'CUES', model: 'FC-U8000-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'CUES', model: 'FC-U6000-1', system: 'Drivetrain', size: '1x10' },
    { name: 'Crankset', brand: 'Shimano', series: 'CUES', model: 'FC-U6000-2', system: 'Drivetrain', size: '2x10' },
    { name: 'Crankset', brand: 'Shimano', series: 'CUES', model: 'FC-U4000-1', system: 'Drivetrain', size: '1x9' },
    { name: 'Cassette', brand: 'Shimano', series: 'CUES', model: 'CS-LG600-11', system: 'Drivetrain', size: '11' },
    { name: 'Cassette', brand: 'Shimano', series: 'CUES', model: 'CS-LG400-10', system: 'Drivetrain', size: '10' },
    { name: 'Cassette', brand: 'Shimano', series: 'CUES', model: 'CS-LG300-9', system: 'Drivetrain', size: '9' },
    { name: 'Chain', brand: 'Shimano', series: 'CUES', model: 'CN-LG500', system: 'Drivetrain', size: '11/10/9' },
    { name: 'Hub', brand: 'Shimano', series: 'CUES', model: 'FH-U8000', system: 'Wheelset', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'CUES', model: 'FH-U6000', system: 'Wheelset', size: '10' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'CUES', model: 'BL-U8000', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'CUES', model: 'BR-U8000', system: 'Brakes' },

    // Deore
    { name: 'Shifter', brand: 'Shimano', series: 'Deore', model: 'SL-M6100', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Deore', model: 'SL-M5100', system: 'Drivetrain', size: '11' },
    { name: 'Shifter', brand: 'Shimano', series: 'Deore', model: 'SL-M4100', system: 'Drivetrain', size: '10' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Deore', model: 'FD-M6100', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Deore', model: 'FD-M5100', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Deore', model: 'RD-M6100', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Deore', model: 'RD-M5100', system: 'Drivetrain', size: '11' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Deore', model: 'RD-M4100', system: 'Drivetrain', size: '10' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore', model: 'FC-M6100-1', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore', model: 'FC-M6100-2', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore', model: 'FC-M5100-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore', model: 'FC-M5100-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore', model: 'FC-M4100-2', system: 'Drivetrain', size: '2x10' },
    { name: 'Cassette', brand: 'Shimano', series: 'Deore', model: 'CS-M6100', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'Deore', model: 'CS-M5100-11', system: 'Drivetrain', size: '11' },
    { name: 'Cassette', brand: 'Shimano', series: 'Deore', model: 'CS-M4100-10', system: 'Drivetrain', size: '10' },
    { name: 'Chain', brand: 'Shimano', series: 'Deore', model: 'CN-M6100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'Deore', model: 'CN-HG601-11', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'Deore', model: 'CN-HG54', system: 'Drivetrain', size: '10' },
    { name: 'Hub', brand: 'Shimano', series: 'Deore', model: 'FH-M6100', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: 'Deore', model: 'FH-M5100', system: 'Wheelset', size: '11' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Deore', model: 'BL-M6100', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Deore', model: 'BR-M6100', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Deore', model: 'BL-MT401', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Deore', model: 'BR-MT400', system: 'Brakes' },
    
    // Deore XT
    { name: 'Shifter', brand: 'Shimano', series: 'Deore XT', model: 'SL-M8100', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'Deore XT', model: 'SL-M8000', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Deore XT', model: 'FD-M8100', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Deore XT', model: 'FD-M8020', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Deore XT', model: 'RD-M8100', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Deore XT', model: 'RD-M8000', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore XT', model: 'FC-M8100-1', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore XT', model: 'FC-M8100-2', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore XT', model: 'FC-M8000-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'Deore XT', model: 'FC-M8000-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Shimano', series: 'Deore XT', model: 'CS-M8100-12', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'Deore XT', model: 'CS-M8000', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'Deore XT', model: 'CN-M8100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'Deore XT', model: 'CN-HG701-11', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'Deore XT', model: 'FH-M8110', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: 'Deore XT', model: 'FH-M8000', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Shimano', series: 'Deore XT', model: 'WH-M8100-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'Deore XT', model: 'WH-M8100-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Deore XT', model: 'BL-M8100', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Deore XT', model: 'BR-M8100', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Deore XT', model: 'BL-M8000', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Deore XT', model: 'BR-M8000', system: 'Brakes' },

    // XTR
    { name: 'Shifter', brand: 'Shimano', series: 'XTR', model: 'SL-M9100', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'Shimano', series: 'XTR', model: 'SL-M9000', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'XTR', model: 'FD-M9100', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'XTR', model: 'FD-M9020', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'XTR', model: 'RD-M9100', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'XTR', model: 'RD-M9000', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'Shimano', series: 'XTR', model: 'FC-M9100-1', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'XTR', model: 'FC-M9100-2', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'Shimano', series: 'XTR', model: 'FC-M9000-1', system: 'Drivetrain', size: '1x11' },
    { name: 'Crankset', brand: 'Shimano', series: 'XTR', model: 'FC-M9000-2', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'Shimano', series: 'XTR', model: 'CS-M9100', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'Shimano', series: 'XTR', model: 'CS-M9000', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'Shimano', series: 'XTR', model: 'CN-M9100', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'Shimano', series: 'XTR', model: 'CN-HG901-11', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'Shimano', series: 'XTR', model: 'FH-M9110', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'Shimano', series: 'XTR', model: 'FH-M9000', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'Shimano', series: 'XTR', model: 'WH-M9100-TL', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'Shimano', series: 'XTR', model: 'WH-M9100-TL', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'XTR', model: 'BL-M9100', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'XTR', model: 'BR-M9100', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'XTR', model: 'BL-M9000', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'XTR', model: 'BR-M9000', system: 'Brakes' },

    // Saint
    { name: 'Shifter', brand: 'Shimano', series: 'Saint', model: 'SL-M820', system: 'Drivetrain', size: '10' },
    { name: 'Front Derailleur', brand: 'Shimano', series: 'Saint', model: 'N/A', system: 'Drivetrain' },
    { name: 'Rear Derailleur', brand: 'Shimano', series: 'Saint', model: 'RD-M820', system: 'Drivetrain', size: '10' },
    { name: 'Crankset', brand: 'Shimano', series: 'Saint', model: 'FC-M820', system: 'Drivetrain', size: '1x10' },
    { name: 'Cassette', brand: 'Shimano', series: 'Saint', model: 'CS-M771-10', system: 'Drivetrain', size: '10' },
    { name: 'Chain', brand: 'Shimano', series: 'Saint', model: 'CN-HG95', system: 'Drivetrain', size: '10' },
    { name: 'Hub', brand: 'Shimano', series: 'Saint', model: 'FH-M820', system: 'Wheelset', size: '10' },
    { name: 'Brake Lever', brand: 'Shimano', series: 'Saint', model: 'BL-M820', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'Shimano', series: 'Saint', model: 'BR-M820', system: 'Brakes' },
];
