
type ShoeComponent = {
    name: 'Cycling Shoes';
    brand: string;
    model: string;
    discipline: 'Road' | 'MTB' | 'Gravel';
    system: 'Accessories';
};

export const SHOE_COMPONENTS: ShoeComponent[] = [
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Shot 2', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Sixty', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Wire 2 Carbon', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Genius 10', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Ergo 5', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'S-PHYRE RC903', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'RC7', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'RC5', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'RP5', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'TR9', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'IC5', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'S-Works Torch', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'S-Works 7', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Torch 3.0', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Torch 2.0', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Torch 1.0', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Ares', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Imperial', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Empire SLX', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Regime', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Cadet', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Synthe', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Vento Stabilita Carbon', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Vento Infinito Carbon 2', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Vento Decos Carbon', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Tempo R5 Powerstrap', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Tempo Overcurve R4', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bont', model: 'Vaypor S', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bont', model: 'Helix', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'XXX Road', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'Specter', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'Meraj', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.Stilo Carbon', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.Chrono', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'DMT', model: 'KR SL', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'DMT', model: 'KR1', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Quoc', model: 'Mono II', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Louis Garneau', model: 'Course Air Lite II', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Louis Garneau', model: 'Carbon Pro 3', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Scott', model: 'Road RC Ultimate', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Scott', model: 'Road Comp Boa', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'CX403', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'CX241', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'CX238', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Leatt', model: 'DBX 5.0', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Rapha', model: 'Pro Team', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Rapha', model: 'Classic', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Ekoi', model: 'R4 Evo', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Ekoi', model: 'R5', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Suplest', model: 'Edge+ Road Pro', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Suplest', model: 'StreetRacing', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Mavic', model: 'Cosmic Ultimate SL', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Mavic', model: 'Cosmic Boa', discipline: 'Road', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Tiger 2 SRS', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Dragon 5', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'SD15', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'S-PHYRE XC902', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'XC702', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'ME702', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'AM903', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'GR9', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'S-Works Recon', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Recon 3.0', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: '2FO Roost', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: '2FO DH Clip', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: '2FO Cliplite', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Chrono Expert', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Terraduro', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Rumble VR', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Vento Ferox Carbon', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Terra Ergolace X2', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Gravity Alpaca', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Five Ten', model: 'Freerider Pro', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Five Ten', model: 'Impact Pro', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Five Ten', model: 'Trailcross LT', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'XXX Mountain', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'Rally', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'Foray', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.All Terrain', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.Kobra', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Scott', model: 'MTB RC Ultimate', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Scott', model: 'MTB Comp Boa', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'MX238', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'MX237', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Leatt', model: '2.0 Flat', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Leatt', model: '5.0 Clipless', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Pearl Izumi', model: 'X-Alp', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Pearl Izumi', model: 'X-Alp Flow', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Ride Concepts', model: 'Hellion', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Ride Concepts', model: 'Livewire', discipline: 'MTB', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'Gravel Ghibli', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Sidi', model: 'MTB Trace 2', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'RX8', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'RX6', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Shimano', model: 'XC5', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'S-Works Recon Lace', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Specialized', model: 'Recon 2.0', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Cylinder', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Privateer Lace', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Giro', model: 'Regime', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Terra Atlas', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Fizik', model: 'Terra Powerstrap X4', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Bontrager', model: 'GR2', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Lake', model: 'MX238', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Quoc', model: 'Gran Tourer', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Quoc', model: 'Weekend', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Louis Garneau', model: 'Gravier', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Pearl Izumi', model: 'X-Alp Summit', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Pearl Izumi', model: 'X-Alp Gravel', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Scott', model: 'MTB Comp Boa', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.Hurricane', discipline: 'Gravel', system: 'Accessories' },
    { name: 'Cycling Shoes', brand: 'Gaerne', model: 'G.Trail', discipline: 'Gravel', system: 'Accessories' },
];
