
type SramComponent = {
    name: string;
    brand: 'SRAM';
    series: string;
    model: string;
    system: 'Drivetrain' | 'Brakes' | 'Wheelset';
    size?: string;
};

export const SRAM_COMPONENTS: SramComponent[] = [
    // Red
    { name: 'Shifter', brand: 'SRAM', series: 'Red', model: 'Force eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Red', model: 'Red eTap AXS HRD', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Red', model: 'Red eTap HRD', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Red', model: 'Red eTap AXS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Red', model: 'Red eTap', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Red', model: 'Red eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Red', model: 'Red eTap', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'SRAM', series: 'Red', model: 'Red AXS Power Meter', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Red', model: 'Red AXS Power Meter', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Red', model: 'Red DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Red', model: 'Red DUB', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Red', model: 'Red 22', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'SRAM', series: 'Red', model: 'XG-1290', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Red', model: 'XG-1190', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'SRAM', series: 'Red', model: 'Flattop', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Red', model: 'Red 22', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'SRAM', series: 'Red', model: 'Cognition Disc', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Red', model: 'Cognition', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'SRAM', series: 'Red', model: 'Zipp 303 Firecrest', system: 'Wheelset' },
    { name: 'Rim', brand: 'SRAM', series: 'Red', model: 'Zipp 404 Firecrest', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'SRAM', series: 'Red', model: 'Zipp 303 Firecrest', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'SRAM', series: 'Red', model: 'Zipp 404 Firecrest', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Red', model: 'Red eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Red', model: 'Red eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Red', model: 'Red HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Red', model: 'Red HRD', system: 'Brakes' },

    // Force
    { name: 'Shifter', brand: 'SRAM', series: 'Force', model: 'Force eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Force', model: 'Force 22', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Force', model: 'Force eTap AXS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Force', model: 'Force 22', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Force', model: 'Force eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Force', model: 'Force 22', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'SRAM', series: 'Force', model: 'Force DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Force', model: 'Force DUB', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Force', model: 'Force 22', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'SRAM', series: 'Force', model: 'XG-1270', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Force', model: 'XG-1170', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'SRAM', series: 'Force', model: 'Flattop', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Force', model: 'PC-1170', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'SRAM', series: 'Force', model: 'Disc', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Force', model: 'Disc', system: 'Wheelset', size: '11' },
    { name: 'Rim', brand: 'SRAM', series: 'Force', model: 'Zipp 303 S', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'SRAM', series: 'Force', model: 'Zipp 303 S', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Force', model: 'Force eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Force', model: 'Force eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Force', model: 'Force HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Force', model: 'Force HRD', system: 'Brakes' },

    // Rival
    { name: 'Shifter', brand: 'SRAM', series: 'Rival', model: 'Rival eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Rival', model: 'Rival 22', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Rival', model: 'Rival eTap AXS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Rival', model: 'Rival 22', system: 'Drivetrain', size: '2' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Rival', model: 'Rival eTap AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Rival', model: 'Rival 22', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'SRAM', series: 'Rival', model: 'Rival DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Rival', model: 'Rival DUB', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Rival', model: 'Rival 22', system: 'Drivetrain', size: '2x11' },
    { name: 'Cassette', brand: 'SRAM', series: 'Rival', model: 'XG-1250', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Rival', model: 'PG-1130', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'SRAM', series: 'Rival', model: 'Flattop', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Rival', model: 'PC-1130', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'SRAM', series: 'Rival', model: 'Disc', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Rival', model: 'Disc', system: 'Wheelset', size: '11' },
    { name: 'Wheelset', brand: 'SRAM', series: 'Rival', model: 'DT Swiss G 1800', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Rival', model: 'Rival eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Rival', model: 'Rival eTap AXS HRD', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Rival', model: 'Rival HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Rival', model: 'Rival HRD', system: 'Brakes' },

    // Apex
    { name: 'Shifter', brand: 'SRAM', series: 'Apex', model: 'Apex AXS', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Apex', model: 'Apex 1', system: 'Drivetrain', size: '11' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Apex', model: 'Apex AXS', system: 'Drivetrain', size: '2' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Apex', model: 'Apex 1 (N/A)', system: 'Drivetrain', size: '1' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Apex', model: 'Apex AXS XPLR', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Apex', model: 'Apex 1', system: 'Drivetrain', size: '11' },
    { name: 'Crankset', brand: 'SRAM', series: 'Apex', model: 'Apex DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Apex', model: 'Apex DUB', system: 'Drivetrain', size: '2x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Apex', model: 'Apex 1', system: 'Drivetrain', size: '1x11' },
    { name: 'Cassette', brand: 'SRAM', series: 'Apex', model: 'PG-1231', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Apex', model: 'PG-1130', system: 'Drivetrain', size: '11' },
    { name: 'Chain', brand: 'SRAM', series: 'Apex', model: 'Flattop', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Apex', model: 'PC-1110', system: 'Drivetrain', size: '11' },
    { name: 'Hub', brand: 'SRAM', series: 'Apex', model: 'Disc', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Apex', model: 'Disc', system: 'Wheelset', size: '11' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Apex', model: 'Apex AXS HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Apex', model: 'Apex AXS HRD', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Apex', model: 'Apex 1 HRD', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Apex', model: 'Apex 1 HRD', system: 'Brakes' },

    // Eagle
    { name: 'Shifter', brand: 'SRAM', series: 'Eagle', model: 'Eagle AXS (various)', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Eagle', model: 'NX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Shifter', brand: 'SRAM', series: 'Eagle', model: 'SX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Front Derailleur', brand: 'SRAM', series: 'Eagle', model: 'N/A', system: 'Drivetrain', size: '1' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Eagle', model: 'XX1 Eagle AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Eagle', model: 'X01 Eagle AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Eagle', model: 'GX Eagle AXS', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Eagle', model: 'NX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Rear Derailleur', brand: 'SRAM', series: 'Eagle', model: 'SX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Eagle', model: 'XX1 Eagle DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Eagle', model: 'X01 Eagle DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Eagle', model: 'GX Eagle DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Eagle', model: 'NX Eagle DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Crankset', brand: 'SRAM', series: 'Eagle', model: 'SX Eagle DUB', system: 'Drivetrain', size: '1x12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Eagle', model: 'XG-1299', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Eagle', model: 'XG-1275', system: 'Drivetrain', size: '12' },
    { name: 'Cassette', brand: 'SRAM', series: 'Eagle', model: 'PG-1230', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Eagle', model: 'XX1 Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Eagle', model: 'X01 Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Eagle', model: 'GX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Eagle', model: 'NX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Chain', brand: 'SRAM', series: 'Eagle', model: 'SX Eagle', system: 'Drivetrain', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Eagle', model: 'XD Driver', system: 'Wheelset', size: '12' },
    { name: 'Hub', brand: 'SRAM', series: 'Eagle', model: 'HG Driver', system: 'Wheelset', size: '12' },
    { name: 'Rim', brand: 'SRAM', series: 'Eagle', model: 'Zipp 3ZERO MOTO', system: 'Wheelset' },
    { name: 'Wheelset', brand: 'SRAM', series: 'Eagle', model: 'Zipp 3ZERO MOTO', system: 'Wheelset' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Eagle', model: 'Level Ultimate', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Eagle', model: 'Level Ultimate', system: 'Brakes' },
    { name: 'Brake Lever', brand: 'SRAM', series: 'Eagle', model: 'G2 Ultimate', system: 'Brakes' },
    { name: 'Brake Caliper', brand: 'SRAM', series: 'Eagle', model: 'G2 Ultimate', system: 'Brakes' },
];
