steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="firebase-api-key" --format='get(payload.data)' | tr '_-' '/+' | base64 -d > .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-auth-domain" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-project-id" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-storage-bucket" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-messaging-sender-id" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-app-id" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="firebase-measurement-id" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
        echo "" >> .env
        gcloud secrets versions access latest --secret="gemini-api-key" --format='get(payload.data)' | tr '_-' '/+' | base64 -d >> .env
  - name: 'us-central1-docker.pkg.dev/serverless-runtimes/google-22/buildpacks/nodejs:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp .env .next/
        /cnb/buildpacks/google.nodejs.runtime/1.0.0/bin/build
        /cnb/buildpacks/google.nodejs.firebasenextjs/0.0.1/bin/build
        /cnb/buildpacks/google.nodejs.npm/1.1.0/bin/build
        /cnb/buildpacks/google.nodejs.firebasebundle/0.0.1/bin/build
        /cnb/lifecycle/creator \
          -app /workspace \
          -cache-dir /cache \
          -log-level=debug \
          -run-image=us-central1-docker.pkg.dev/serverless-runtimes/google-22/run/base:public-image-next \
          us-central1-docker.pkg.dev/$PROJECT_ID/firebaseapphosting-images/eqpmgr:build-$(date +%Y-%m-%d-%H%M)
    secretManager:
      - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
        env: 'firebase-api-key'
      - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
        env: 'firebase-auth-domain'
      - versionName: projects/$PROJECT_ID/secrets/firebase-project-id/versions/latest
        env: 'firebase-project-id'
      - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
        env: 'firebase-storage-bucket'
      - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
        env: 'firebase-messaging-sender-id'
      - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
        env: 'firebase-app-id'
      - versionName: projects/$PROJECT_ID/secrets/firebase-measurement-id/versions/latest
        env: 'firebase-measurement-id'
      - versionName: projects/$PROJECT_ID/secrets/gemini-api-key/versions/latest
        env: 'gemini-api-key'
      - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
        env: 'GOOGLE_APPLICATION_CREDENTIALS_JSON'
options:
  logging: CLOUD_LOGGING_ONLY
  secretManager:
      - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
      - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - versionName: projects/$PROJECT_ID/secrets/firebase-project-id/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
      - versionName: projects/$PROJECT_ID/secrets/firebase-measurement-id/versions/latest
        env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
      - versionName: projects/$PROJECT_ID/secrets/gemini-api-key/versions/latest
        env: 'GEMINI_API_KEY'
      - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
        env: 'GOOGLE_APPLICATION_CREDENTIALS_JSON'
timeout: 3600s