steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    secretEnv:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-api-key/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/firebase-auth-domain/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/firebase-project-id/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/firebase-storage-bucket/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/firebase-messaging-sender-id/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/firebase-app-id/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/firebase-measurement-id/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
